version: '3.4'

services:
  caseworker:
    env_file:
      - ./caseworker.env
    build: .
    volumes:
      - .:/app
    ports:
      - 8200:8200
    expose:
      - 8200
    command: ./manage.py runserver 0.0.0.0:${PORT:-8200}
    networks:
      - lite
    stdin_open: true
    tty: true

  exporter:
    env_file:
      - ./exporter.env
    build: .
    volumes:
      - .:/app
    ports:
      - 8300:8300
    expose:
      - 8300
    command: ./manage.py runserver 0.0.0.0:${PORT:-8300}
    networks:
      - lite
    stdin_open: true
    tty: true

networks:
  lite:
    external: true
