version: 2.1

orbs:
  jq: circleci/jq@1.8.0

###############################################################################
# Images
###############################################################################

image_python: &image_python
  image: circleci/python:3.7

image_postgres: &image_postgres
  image: circleci/postgres:9.5-alpine-ram
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres

###############################################################################
# Steps
###############################################################################

lint_steps: &lint_steps
  steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: pipenv sync --dev
    - run: pipenv run bandit -r .
    - run: pipenv run prospector
    - run: pipenv run black . --check --diff

pytest_steps: &pytest_steps
  steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: pipenv sync --dev
    - run: pipenv run pytest

###############################################################################
# Jobs
###############################################################################

jobs:
  lint:
    docker:
      - <<: *image_python
    <<: *lint_steps

  caseworker_test:
    docker:
      - <<: *image_python
      - <<: *image_postgres
    environment:
      PIPENV_VENV_IN_PROJECT: enabled
      PIPENV_DOTENV_LOCATION: example.caseworker.env
      PYTEST_ADDOPTS: unit_tests/caseworker --capture=no --nomigrations
    <<: *pytest_steps

  exporter_test:
    docker:
      - <<: *image_python
      - <<: *image_postgres
    environment:
      PIPENV_VENV_IN_PROJECT: enabled
      PIPENV_DOTENV_LOCATION: example.exporter.env
      PYTEST_ADDOPTS: unit_tests/exporter --capture=no --nomigrations
    <<: *pytest_steps

workflows:
  version: 2
  test:
    jobs:
      - lint
      - caseworker_test
      - exporter_test
